### ISSUE TITLE
训练超参数

### ISSUE THREAD

**Issue by zly1213811** [zhouchenlin2096/QKFormer#4]
你好，请问可以告知一下训练时的超参数吗，如学习率之类的，非常感谢！

**Comment by zhouchenlin2096** [comment]
学习率的话，使用上传代码默认设置的超参数应该就没问题。代码主要调整超参的地方就是跑imageNet的时候，64M参数的时候会降低batch size (显卡内存原因)。至于其他超参数使用默认设置应该也没问题。
