### ISSUE TITLE
是否可以提供计算能耗的代码？

### ISSUE THREAD

**Issue by kurie21** [zhouchenlin2096/QKFormer#7]
祝贺您的工作中了NeurIPS，恭喜！同时非常感谢您的工作，我获益匪浅！

但我在计算能耗时遇到了一点问题。
我尝试使用您在spikingformer仓库提供的计算能耗的代码计算QKFormer的能耗，报错了；然后我修改后，发现得出的结果还是有问题。
想问您是否可以提供您计算QKFormer能耗时使用的代码？非常感谢！

**Comment by zhouchenlin2096** [comment]
QKFormer主要的实验结果使用的是Sew-resnet、spikformer中的残差。为方便对比，所以能耗计算方式也是和spikformer的计算方式一致。计算过程根据spikformer作者告知后人工计算的，没有代码。论文种我也补充了spikingformer中残差的ablation study。
