### ISSUE TITLE
Alternative download links?

### ISSUE THREAD

**Issue by williford** [zhouchenlin2096/QKFormer#8]
Congrats on your excellent work and thanks for sharing it.

Would you be able to make the pretrained models available on additional services outside of China, like on Google Drive, OneDrive, or Torrents w/ md5sum hashes?

Thanks!

**Comment by zhouchenlin2096** [comment]
QKFormer models download link（Google Drive）：https://drive.google.com/drive/folders/1vhq9jmhmuyZ5_RGHuWD4wniza856qF8U?usp=drive_link

**Comment by williford** [comment]
Thanks a lot!

FYI, for anyone interested, here is the m5sum I got:

```
60df416983ae326bb14bdb4566444320  output_dir_qkformer_78.85/checkpoint-199.pth
85dd1f94c87ba5ec908fed5d0a3f7f69  output_dir_qkformer_82.08/checkpoint-196.pth
dc1595408ed1bd40346be2bdaf5015d5  output_dir_qkformer_84.29/checkpoint-191.pth
ba20af8eb450d4ec9c71009fde8e7125  output_dir_qkformer_85.3/checkpoint-217.pth
99a671118f67a680aa38b6ac5aae449a  output_dir_qkformer_85.65/checkpoint-203.pth
```

The 78.85 indicates the Imagenet accuracy (or at least approximate accuracy?). Hence, they are in the same order as the main page.

**Comment by Rangs02245** [comment]
Hi authors, I find that the pretrained checkpoints link is no longer available, can you update the link? many thanks for your contributions!
